mqtt_client:
  ros__parameters:
    broker:
      host: "<VPS_PUBLIC_IP>"
      port: 1883
    bridge:
      # Dari ROS2 ke MQTT (publish dari robot ke VPS)
      ros2mqtt:
        - ros_topic: "/chatter"
          mqtt_topic: "robot/chatter"
          primitive: true
      # Dari MQTT ke ROS2 (subscribe dari VPS untuk dikirim ke robot)
      mqtt2ros:
        - mqtt_topic: "robot/cmd_vel"
          ros_topic: "/cmd_vel"
          primitive: true
